REMOVE="
/system/product/priv-app/GmsCore
/system/product/priv-app/PrebuiltGmsCore
/system/product/priv-app/GoogleServicesFramework
/system/product/priv-app/Phonesky
/system/priv-app/GmsCore
/system/priv-app/PrebuiltGmsCore
/system/priv-app/GoogleServicesFramework
/system/priv-app/Phonesky
/system/system_ext/priv-app/GoogleServicesFramework
"